# Generated by Django 5.0.1 on 2024-12-11 06:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text="Customer's monthly salary in the local currency", max_digits=10)),
                ('approved_limit', models.DecimalField(decimal_places=2, help_text='Total credit limit approved for the customer', max_digits=10)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding debt for the customer', max_digits=10)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the loan', max_digits=12)),
                ('tenure', models.DecimalField(decimal_places=0, help_text='Loan tenure in months', max_digits=32)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate for the loan', max_digits=5)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, help_text='Monthly Equated Monthly Installment (EMI)', max_digits=10)),
                ('emis_paid_on_time', models.DecimalField(decimal_places=0, help_text='Number of EMIs paid on time', max_digits=32)),
                ('start_date', models.DateField(help_text='Date when the loan was initiated')),
                ('end_date', models.DateField(help_text='Date when the loan is scheduled to be fully repaid')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='credit_validation_app.customer')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-start_date'],
            },
        ),
    ]
